version: '2'

services:
  server:
    build: .
    ports:
      - "5000:5000"
      - "5858:5858"
    environment:
      PORT: 5000
      KEY: jhgasdkjfhgsdkjfhgsdkfjhg
    volumes:
      - .:/usr/src/app
